// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://xdobitvpzkniggoryfon.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkb2JpdHZwemtuaWdnb3J5Zm9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0NzU5MjgsImV4cCI6MjA0ODA1MTkyOH0.4Xbk3cwCl8ZGJoQLzPQ1C8V_jDmC6ABkTYKgChUwxsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);